name: Hello World Github Actions

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Display message
        run: echo "Hello world GitHub Actions!"